### ISSUE TITLE
footer page new design

### ISSUE THREAD

**Issue by ilyasahmed081** [thrashtechinfo/healthcare-web-app#21]

**Comment by Jitmisra** [comment]
please assign this task to me for Hacktoberfest2024

**Comment by thrashtechinfo** [comment]
@ilyasahmed081 have already started on it @Jitmisra, let assign new task to you. thanks

**Comment by thrashtechinfo** [comment]
@Jitmisra please comment here, i will assign you
https://github.com/thrashtechinfo/healthcare-web-app/issues/22
